### ISSUE TITLE
GUI for 12DOF Robot

### ISSUE THREAD

**Issue by HanTop310** [open-dynamic-robot-initiative/mw_gui_universal#2]
Hi there, wanted to ask if this GUI is compatible with the 12DOF Robot and the Foot Contact Switches.
Also, what computer languages are used to operate the robots (the 12DOF and 8DOF to be exact)

**Comment by jviereck** [comment]
Hi, the GUI is to drive a single motor board. So it won't be enough to drive 12 DOF. The foot contact sensor is based on an analog signal which is I think read by the GUI application.

People use Python or C++ to program the robot.
